type language = {
  name: string
  code: string
}
const languages: language[] = [
  { name: "Afrikaans", code: "af" },
  { name: "Polski", code: "pl" },
  { name: "العربية", code: "ar" },
  { name: "Asturianu", code: "ast" },
  { name: "Azərbaycanca", code: "az" },
  { name: "Български", code: "bg" },
  { name: "閩南語 / Bân-lâm-gú", code: "nan" },
  { name: "বাংলা", code: "bn" },
  { name: "Беларуская", code: "be" },
  { name: "Català", code: "ca" },
  { name: "Čeština", code: "cs" },
  { name: "Cymraeg", code: "cy" },
  { name: "Dansk", code: "da" },
  { name: "Deutsch", code: "de" },
  { name: "Eesti", code: "et" },
  { name: "Ελληνικά", code: "el" },
  { name: "English", code: "en" },
  { name: "Español", code: "es" },
  { name: "Esperanto", code: "eo" },
  { name: "Euskara", code: "eu" },
  { name: "فارسی", code: "fa" },
  { name: "Français", code: "fr" },
  { name: "Galego", code: "gl" },
  { name: "한국어", code: "ko" },
  { name: "Հայերեն", code: "hy" },
  { name: "हिन्दी", code: "hi" },
  { name: "Hrvatski", code: "hr" },
  { name: "Bahasa Indonesia", code: "id" },
  { name: "Italiano", code: "it" },
  { name: "עברית", code: "he" },
  { name: "ქართული", code: "ka" },
  { name: "Ladin", code: "lld" },
  { name: "Latina", code: "la" },
  { name: "Latviešu", code: "lv" },
  { name: "Lietuvių", code: "lt" },
  { name: "Magyar", code: "hu" },
  { name: "Македонски", code: "mk" },
  { name: "مصرى", code: "arz" },
  { name: "Bahasa Melayu", code: "ms" },
  { name: "Bahaso Minangkabau", code: "min" },
  { name: "မြန်မာဘာသာ", code: "my" },
  { name: "Nederlands", code: "nl" },
  { name: "日本語", code: "ja" },
  { name: "Norsk (bokmål)", code: "no" },
  { name: "Norsk (nynorsk)", code: "nn" },
  { name: "Нохчийн", code: "ce" },
  { name: "Oʻzbekcha / Ўзбекча", code: "uz" },
  { name: "Português", code: "pt" },
  { name: "Қазақша / Qazaqşa / قازاقشا", code: "kk" },
  { name: "Română", code: "ro" },
  { name: "Русский", code: "ru" },
  { name: "Simple English", code: "simple" },
  { name: "Sinugboanong Binisaya", code: "ceb" },
  { name: "Slovenčina", code: "sk" },
  { name: "Slovenščina", code: "sl" },
  { name: "Српски / Srpski", code: "sr" },
  { name: "Srpskohrvatski / Српскохрватски", code: "sh" },
  { name: "Suomi", code: "fi" },
  { name: "Svenska", code: "sv" },
  { name: "தமிழ்", code: "ta" },
  { name: "Татарча / Tatarça", code: "tt" },
  { name: "ภาษาไทย", code: "th" },
  { name: "Тоҷикӣ", code: "tg" },
  { name: "تۆرکجه", code: "azb" },
  { name: "Türkçe", code: "tr" },
  { name: "Українська", code: "uk" },
  { name: "اردو", code: "ur" },
  { name: "Tiếng Việt", code: "vi" },
  { name: "Winaray", code: "war" },
  { name: "中文", code: "zh" },
  { name: "粵語", code: "yue" },
]
export default languages
